//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class r_room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public r_room()
        {
            this.re_reservation = new HashSet<re_reservation>();
        }
    
        public int r_number { get; set; }
        public int r_h_hotel { get; set; }
        public Nullable<int> r_beds { get; set; }
        public Nullable<decimal> r_price { get; set; }
        public string r_description { get; set; }
        public string r_tr_typeOfRoom { get; set; }
    
        public virtual h_hotel h_hotel { get; set; }
        public virtual tr_typeOfRoom tr_typeOfRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<re_reservation> re_reservation { get; set; }
    }
}
